CONFIG_NAME: "FinalParamsLarge"
MODEL:
  DROPOUT: 0.25
  RECURRENT_DROPOUT: 0.0
  USE_RNN: True
  RNN: "lstm"
  RNN_SIZE: 300
  USE_CNN: True
  CNN_LAYERS: 2
  NUM_FILTERS: 200
  FILTER_SIZE: 3
  MAX_POOL_SIZE: 2
  CLASSIFIER: "crf"
  EMBEDDING_SIZE: 200
TRAINING:
  DATASET: "english"
  MINI_BATCH_SIZE: 64
  EPOCHS: 5
DATASET:
  CUSTOM_EMBEDDINGS: True
  EMBEDDING_NAME: 'glove-200d-vectors.txt'
  EMBEDDING_TYPE: 'txt'
  FILETYPE: 'txt'
